// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func ProvideCar(c string) Car {
	wheel := NewWheel(c)
	body := NewBody(wheel)
	car := NewCar(body)
	return car
}
