// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func ProvideCar() Car {
	wheel := setupWheel()
	body := NewBody(wheel)
	car := NewCar(body)
	return car
}

// wire.go:

func setupWheel() Wheel {
	return Wheel{}
}
