// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func ProvideCar(c Color, s Style) Car {
	wheel := NewWheel(c, s)
	body := NewBody(wheel)
	car := NewCar(body)
	return car
}
