// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package main

// Injectors from wire.go:

func ProvideCar() Car {
	wheel := NewWheel()
	body := NewBody()
	carConfig := &CarConfig{
		w: wheel,
		b: body,
	}
	car := NewCar(carConfig)
	return car
}
